<?php

/**
 * @file
 * Paragraph columns module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

function par_cards_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'par_cards/cards';
}


/**
 * Implements hook_theme().
 */
function par_cards_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__paragraph_card' => [
      'base hook' => 'paragraph',
    ],
  ];
}
